// Generated by CoffeeScript 1.7.1
(function() {
  this.HTML5Slider = function(config) {
    return new HTML5Slider[this.getBuilder(config)](config);
  };

  this.HTML5Slider.prototype = {
    extend: function(pObj, pVal) {
      var i, _results;
      _results = [];
      for (i in pVal) {
        _results.push(pObj[i] = pVal[i]);
      }
      return _results;
    },
    getChildren: function(elem, callback) {
      var chLength, children, i;
      children = elem.children;
      chLength = children.length;
      if (!chLength) {
        throw new Error(elem.id + ' - children not found');
      }
      if (chLength === 1) {
        console.warn('only one child in ' + elem.id);
      }
      if (!callback) {
        return children;
      }
      i = 0;
      while (i < chLength) {
        children[i].style.position = 'absolute';
        callback(children[i]);
        i++;
      }
      return children;
    },
    isPauseOnHover: function(config) {
      if (!config.pauseOnHover) {
        return false;
      }
      if (config.obj.parentElement.querySelector(':hover') === config.obj) {
        return true;
      }
    },
    getBuilder: function(config) {
      var name;
      name = 'Slide';
      if (config.type === 'scrollX') {
        name = 'ScrollX';
      } else if (config.type === 'scrollY') {
        name = 'ScrollY';
      }
      return name;
    }
  };

}).call(this);

//# sourceMappingURL=HTML5Slider.map
